# render.yaml
# Render サービス定義（Web Service + Background Worker）

services:
  # ========================================
  # Web Service: FastAPI
  # ========================================
  - type: web
    name: jba-backend
    env: python
    region: singapore  # 東京リージョンがないためシンガポール
    plan: free  # 無料プラン
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    
    # 環境変数
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: API_HOST
        value: 0.0.0.0
      
      - key: API_PORT
        fromService:
          type: web
          name: jba-backend
          property: port
      
      # Supabase（Renderの環境変数設定で追加）
      - key: SUPABASE_URL
        sync: false
      
      - key: SUPABASE_KEY
        sync: false
      
      - key: OUTPUT_BUCKET
        value: outputs
      
      # Redis（Renderの環境変数設定で追加）
      - key: REDIS_URL
        sync: false
      
      - key: CACHE_TYPE
        value: redis
      
      # キャッシュ設定
      - key: CACHE_FILE_PATH
        value: /tmp/jba_player_cache.json
      
      # 出力設定（/tmp は Render で書き込み可能）
      - key: OUTPUT_DIR
        value: /tmp/outputs
      
      - key: JOB_META_DIR
        value: /tmp/temp_results
      
      # ワーカー設定
      - key: MAX_WORKERS
        value: 5
      
      - key: ENABLE_PARALLEL
        value: true
      
      # ログ設定
      - key: LOG_LEVEL
        value: INFO
      
      - key: LOG_FORMAT
        value: json
      
      # 機能フラグ
      - key: USE_SUPABASE_STORAGE
        value: true
      
      - key: USE_SUPABASE_JOBS
        value: true
    
    # ヘルスチェック
    healthCheckPath: /health
    
    # 自動スケール（無料プランは1インスタンス）
    autoDeploy: true
  
  # ========================================
  # Background Worker: PDF生成ワーカー
  # ========================================
  - type: worker
    name: jba-worker
    env: python
    region: singapore
    plan: free  # 無料プラン
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python worker/worker_runner.py
    
    # Web Service と同じ環境変数を使用
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      
      - key: SUPABASE_URL
        sync: false
      
      - key: SUPABASE_KEY
        sync: false
      
      - key: OUTPUT_BUCKET
        value: outputs
      
      - key: REDIS_URL
        sync: false
      
      - key: CACHE_TYPE
        value: redis
      
      - key: CACHE_FILE_PATH
        value: /tmp/jba_player_cache.json
      
      - key: OUTPUT_DIR
        value: /tmp/outputs
      
      - key: JOB_META_DIR
        value: /tmp/temp_results
      
      - key: MAX_WORKERS
        value: 5
      
      - key: ENABLE_PARALLEL
        value: true
      
      - key: LOG_LEVEL
        value: INFO
      
      - key: LOG_FORMAT
        value: json
      
      - key: USE_SUPABASE_STORAGE
        value: true
      
      - key: USE_SUPABASE_JOBS
        value: true
      
      # ワーカー固有の設定
      - key: WORKER_MODE
        value: true
      
      - key: WORKER_POLL_INTERVAL
        value: 5  # 5秒ごとにジョブをチェック
    
    # 自動デプロイ
    autoDeploy: true

# 注意事項:
# 1. `sync: false` の環境変数は Render Dashboard で手動設定が必要
# 2. 無料プランはスリープあり（15分非アクティブで停止）
# 3. /tmp 以外のファイルシステムは読み取り専用
# 4. 永続ストレージは Supabase Storage を使用すること

